/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contoh1;

/**
 *
 * @author Iqbal Atma
 */
public class frm_contoh1 extends javax.swing.JFrame {

    /**
     * Creates new form frm_contoh1
     */
    public frm_contoh1() {
        initComponents();
    }
    public int a,b,c;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_header = new javax.swing.JLabel();
        label_nilai1 = new javax.swing.JLabel();
        label_nilai2 = new javax.swing.JLabel();
        field_nilai1 = new javax.swing.JTextField();
        field_nilai2 = new javax.swing.JTextField();
        jumlahkan = new javax.swing.JButton();
        label_hasil = new javax.swing.JLabel();
        field_hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 63, 90));

        label_header.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        label_header.setText("PENJUMLAHAN");

        label_nilai1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label_nilai1.setText("Nilai 1");

        label_nilai2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label_nilai2.setText("Nilai 2");

        field_nilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nilai1ActionPerformed(evt);
            }
        });

        field_nilai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nilai2ActionPerformed(evt);
            }
        });

        jumlahkan.setText("Jumlahkan");
        jumlahkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlahkanMouseClicked(evt);
            }
        });
        jumlahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahkanActionPerformed(evt);
            }
        });

        label_hasil.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label_hasil.setText("Hasil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(label_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nilai1)
                    .addComponent(label_nilai2)
                    .addComponent(label_hasil))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jumlahkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_nilai1)
                    .addComponent(field_nilai2)
                    .addComponent(field_hasil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(label_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nilai1)
                    .addComponent(field_nilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_nilai2)
                    .addComponent(field_nilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jumlahkan)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_hasil)
                    .addComponent(field_hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        label_nilai1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_nilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nilai1ActionPerformed

    private void jumlahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahkanActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jumlahkanActionPerformed

    private void field_nilai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nilai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nilai2ActionPerformed
    
    private void jumlahkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahkanMouseClicked
        // TODO add your handling code here:
        a = Integer.parseInt(field_nilai1.getText());
        b = Integer.parseInt(field_nilai2.getText());
        c = a+b;
        
        field_hasil.setText(String.valueOf(c));
    }//GEN-LAST:event_jumlahkanMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_contoh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_contoh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_contoh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_contoh1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_contoh1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field_hasil;
    private javax.swing.JTextField field_nilai1;
    private javax.swing.JTextField field_nilai2;
    private javax.swing.JButton jumlahkan;
    private javax.swing.JLabel label_hasil;
    private javax.swing.JLabel label_header;
    private javax.swing.JLabel label_nilai1;
    private javax.swing.JLabel label_nilai2;
    // End of variables declaration//GEN-END:variables
}
